// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: cart.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "CART_SERVICE";

/** ==================== AddCartItem ====================// */
export interface AddCartItemRequest {
  processId?: string | undefined;
  userId: string;
  productId: string;
  skuId: string;
  shopId: string;
  quantity: number;
  skuValue: string;
  productName: string;
  productImage: string;
}

export interface CartItemResponse {
  id: string;
  cartId: string;
  productId: string;
  skuId: string;
  shopId: string;
  quantity: number;
  productName: string;
  skuValue: string;
  productImage: string;
  createdAt: string;
  updatedAt: string;
}

export interface AddCartItemResponse {
  cartItem: CartItemResponse | undefined;
  cartCount: number;
}

/** ==================== ValidateCartItems ====================// */
export interface ValidateCartItemsRequest {
  processId?: string | undefined;
  cartItemIds: string[];
  userId: string;
}

export interface ValidateCartItemsResponse {
  cartItems: CartItemResponse[];
}

export const CART_SERVICE_PACKAGE_NAME = "CART_SERVICE";

export interface CartServiceClient {
  addCartItem(request: AddCartItemRequest): Observable<AddCartItemResponse>;

  validateCartItems(request: ValidateCartItemsRequest): Observable<ValidateCartItemsResponse>;
}

export interface CartServiceController {
  addCartItem(
    request: AddCartItemRequest,
  ): Promise<AddCartItemResponse> | Observable<AddCartItemResponse> | AddCartItemResponse;

  validateCartItems(
    request: ValidateCartItemsRequest,
  ): Promise<ValidateCartItemsResponse> | Observable<ValidateCartItemsResponse> | ValidateCartItemsResponse;
}

export function CartServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addCartItem", "validateCartItems"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CartService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CART_SERVICE_NAME = "CartService";
