// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: media.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "MEDIA_SERVICE";

/** ==================== CreatePresignedUrl ====================// */
export interface CreatePresignedUrlRequest {
  processId?: string | undefined;
  filename: string;
}

export interface CreatePresignedUrlResponse {
  presignedUrl: string;
  url: string;
}

export const MEDIA_SERVICE_PACKAGE_NAME = "MEDIA_SERVICE";

export interface MediaServiceClient {
  createPresignedUrl(request: CreatePresignedUrlRequest): Observable<CreatePresignedUrlResponse>;
}

export interface MediaServiceController {
  createPresignedUrl(
    request: CreatePresignedUrlRequest,
  ): Promise<CreatePresignedUrlResponse> | Observable<CreatePresignedUrlResponse> | CreatePresignedUrlResponse;
}

export function MediaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPresignedUrl"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MediaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MEDIA_SERVICE_NAME = "MediaService";
