// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: order.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ORDER_SERVICE";

export interface CreateOrderRequest {
  processId?: string | undefined;
  userId: string;
  shippingFee: number;
  paymentMethod: string;
  receiver: Receiver | undefined;
  orders: OrderGroup[];
}

export interface Receiver {
  name: string;
  phone: string;
  address: string;
}

export interface OrderGroup {
  shopId: string;
  cartItemIds: string[];
}

export interface CreateOrderResponse {
  orders: Order[];
}

export interface Order {
  id: string;
  userId: string;
  shopId: string;
  grandTotal: number;
  status: string;
}

export const ORDER_SERVICE_PACKAGE_NAME = "ORDER_SERVICE";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest): Observable<CreateOrderResponse>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderRequest,
  ): Promise<CreateOrderResponse> | Observable<CreateOrderResponse> | CreateOrderResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
