// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PAYMENT_SERVICE";

/** ==================== CreatePayment ====================// */
export interface CreatePaymentRequest {
  processId?: string | undefined;
  id: string;
  code: string;
  userId: string;
  orderId: string[];
  method: string;
  status: string;
  amount: number;
}

export interface PaymentResponse {
  id: string;
  code: string;
  userId: string;
  orderId: string;
  method: string;
  status: string;
  amount: number;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export const PAYMENT_SERVICE_PACKAGE_NAME = "PAYMENT_SERVICE";

export interface PaymentServiceClient {
  createPayment(request: CreatePaymentRequest): Observable<PaymentResponse>;
}

export interface PaymentServiceController {
  createPayment(
    request: CreatePaymentRequest,
  ): Promise<PaymentResponse> | Observable<PaymentResponse> | PaymentResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPayment"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
