// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PRODUCT_SERVICE";

/**
 * ======================================// Category ======================================//
 * ==================== GetCategoryRequest ====================//
 */
export interface GetCategoryRequest {
  processId?: string | undefined;
  id: string;
}

export interface CategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyCategoriesRequest ====================// */
export interface GetManyCategoriesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyCategoriesResponse {
  categories: CategoryResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== CreateCategoryRequest ====================// */
export interface CreateCategoryRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
  createdById?: string | undefined;
}

/** ==================== UpdateCategoryRequest ====================// */
export interface UpdateCategoryRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  parentCategoryId?: string | undefined;
  updatedById?: string | undefined;
}

/** ==================== DeleteCategoryRequest ====================// */
export interface DeleteCategoryRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export const PRODUCT_SERVICE_PACKAGE_NAME = "PRODUCT_SERVICE";

export interface ProductServiceClient {
  getCategory(request: GetCategoryRequest): Observable<CategoryResponse>;

  getManyCategories(request: GetManyCategoriesRequest): Observable<GetManyCategoriesResponse>;

  createCategory(request: CreateCategoryRequest): Observable<CategoryResponse>;

  updateCategory(request: UpdateCategoryRequest): Observable<CategoryResponse>;

  deleteCategory(request: DeleteCategoryRequest): Observable<CategoryResponse>;
}

export interface ProductServiceController {
  getCategory(request: GetCategoryRequest): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  getManyCategories(
    request: GetManyCategoriesRequest,
  ): Promise<GetManyCategoriesResponse> | Observable<GetManyCategoriesResponse> | GetManyCategoriesResponse;

  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  updateCategory(
    request: UpdateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  deleteCategory(
    request: DeleteCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getCategory",
      "getManyCategories",
      "createCategory",
      "updateCategory",
      "deleteCategory",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
