// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: product.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PRODUCT_SERVICE";

/** ====================================== Category ======================================// */
export interface ParentCategoryResponse {
  id: string;
  name: string;
}

export interface CategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentCategoryId: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  parentCategory?: ParentCategoryResponse | undefined;
}

/** ==================== CreateCategoryRequest ====================// */
export interface CreateCategoryRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
  createdById?: string | undefined;
}

/** ==================== UpdateCategoryRequest ====================// */
export interface UpdateCategoryRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  parentCategoryId?: string | undefined;
  updatedById?: string | undefined;
}

/** ==================== DeleteCategoryRequest ====================// */
export interface DeleteCategoryRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ========================================== Brand ==========================================// */
export interface BrandResponse {
  id: string;
  name: string;
  logo: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== CreateBrandRequest ====================// */
export interface CreateBrandRequest {
  processId?: string | undefined;
  name: string;
  logo: string;
  createdById?: string | undefined;
}

/** ==================== UpdateBrandRequest ====================// */
export interface UpdateBrandRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  logo?: string | undefined;
  updatedById?: string | undefined;
}

/** ==================== DeleteBrandRequest ====================// */
export interface DeleteBrandRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

/** ======================================== Attribute =========================================// */
export interface AttributeResponse {
  id: string;
  key: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== CreateAttributeRequest ====================// */
export interface CreateAttributeRequest {
  processId?: string | undefined;
  key: string;
  createdById?: string | undefined;
}

/** ==================== UpdateAttributeRequest ====================// */
export interface UpdateAttributeRequest {
  processId?: string | undefined;
  id: string;
  key: string;
  updatedById?: string | undefined;
}

/** ==================== DeleteAttributeRequest ====================// */
export interface DeleteAttributeRequest {
  processId?: string | undefined;
  id: string;
  deletedById?: string | undefined;
}

export const PRODUCT_SERVICE_PACKAGE_NAME = "PRODUCT_SERVICE";

export interface ProductServiceClient {
  createCategory(request: CreateCategoryRequest): Observable<CategoryResponse>;

  updateCategory(request: UpdateCategoryRequest): Observable<CategoryResponse>;

  deleteCategory(request: DeleteCategoryRequest): Observable<CategoryResponse>;

  createBrand(request: CreateBrandRequest): Observable<BrandResponse>;

  updateBrand(request: UpdateBrandRequest): Observable<BrandResponse>;

  deleteBrand(request: DeleteBrandRequest): Observable<BrandResponse>;

  createAttribute(request: CreateAttributeRequest): Observable<AttributeResponse>;

  updateAttribute(request: UpdateAttributeRequest): Observable<AttributeResponse>;

  deleteAttribute(request: DeleteAttributeRequest): Observable<AttributeResponse>;
}

export interface ProductServiceController {
  createCategory(
    request: CreateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  updateCategory(
    request: UpdateCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  deleteCategory(
    request: DeleteCategoryRequest,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  createBrand(request: CreateBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  updateBrand(request: UpdateBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  deleteBrand(request: DeleteBrandRequest): Promise<BrandResponse> | Observable<BrandResponse> | BrandResponse;

  createAttribute(
    request: CreateAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  updateAttribute(
    request: UpdateAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;

  deleteAttribute(
    request: DeleteAttributeRequest,
  ): Promise<AttributeResponse> | Observable<AttributeResponse> | AttributeResponse;
}

export function ProductServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createCategory",
      "updateCategory",
      "deleteCategory",
      "createBrand",
      "updateBrand",
      "deleteBrand",
      "createAttribute",
      "updateAttribute",
      "deleteAttribute",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProductService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCT_SERVICE_NAME = "ProductService";
