// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.4
// source: query.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "QUERY_SERVICE";

/** ====================================== Category ======================================// */
export interface CategoryProduct {
  id: string;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
}

/** ==================== GetCategoryRequest ====================// */
export interface GetCategoryRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetCategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentId?: string | undefined;
  path: string;
  level: number;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyCategoriesRequest ====================// */
export interface GetManyCategoriesRequest {
  processId?: string | undefined;
  parentCategoryId?: string | undefined;
}

export interface GetManyCategoriesResponse {
  categories: GetCategoryResponse[];
}

/**
 * ====================================== Brand ======================================//
 * ==================== GetBrandRequest ====================//
 */
export interface GetBrandRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetBrandResponse {
  id: string;
  name: string;
  logo: string;
  productsCount: number;
  soldCount: number;
  categoryIds: string[];
  categories: CategoryProduct[];
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyBrandsRequest ====================// */
export interface GetManyBrandsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyBrandsResponse {
  brands: GetBrandResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Attribute ======================================//
 * ==================== GetAttributeRequest ====================//
 */
export interface GetAttributeRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetAttributeResponse {
  id: string;
  name: string;
  categoryIds: string[];
  categories: CategoryProduct[];
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyAttributesRequest ====================// */
export interface GetManyAttributesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyAttributesResponse {
  attributes: GetAttributeResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ====================================== Product ======================================// */
export interface Variant {
  value: string;
  options: string[];
}

export interface AttributeProduct {
  name: string;
  value: string;
}

export interface SKU {
  id: string;
  value: string;
  price: number;
  stock: number;
  image?: string | undefined;
}

/** ==================== GetProductRequest ====================// */
export interface GetProductRequest {
  processId?: string | undefined;
  id: string;
  shopId?: string | undefined;
}

export interface GetProductResponse {
  id: string;
  name: string;
  description?: string | undefined;
  provinceId: number;
  districtId: number;
  wardId: number;
  brandId?: string | undefined;
  brandName?: string | undefined;
  brandLogo?: string | undefined;
  categoryIds: string[];
  categories: CategoryProduct[];
  basePrice: number;
  virtualPrice: number;
  minPrice: number;
  maxPrice: number;
  totalStock: number;
  isAvailable: boolean;
  images: string[];
  sizeGuide?: string | undefined;
  variants: Variant[];
  attributes: AttributeProduct[];
  skus: SKU[];
  reviewIds: string[];
  ratingCount: number;
  averageRate: number;
  soldCount: number;
  viewCount: number;
  likeCount: number;
  shopId: string;
  status: string;
  isApproved: boolean;
  isHidden: boolean;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyProductsRequest ====================// */
export interface GetManyProductsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
  status?: string | undefined;
  shopId?: string | undefined;
  brandIds: string[];
  categories: string[];
  minPrice?: number | undefined;
  maxPrice?: number | undefined;
  sortBy?: string | undefined;
  orderBy?: string | undefined;
}

export interface GetManyProductsResponse {
  products: GetProductResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Notifications ======================================//
 * ==================== GetNotificationRequest ====================//
 */
export interface GetNotificationRequest {
  processId?: string | undefined;
  id: string;
  userId: string;
}

/** ==================== GetManyNotificationsRequest ====================// */
export interface GetManyNotificationsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId: string;
}

export interface GetManyNotificationsResponse {
  notifications: NotificationResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface Metadata {
  orderId?: string | undefined;
  articleId?: string | undefined;
}

export interface NotificationResponse {
  id: string;
  userId: string;
  type: string;
  title: string;
  description: string;
  link?: string | undefined;
  image?: string | undefined;
  isRead: boolean;
  metadata?: Metadata | undefined;
  createdAt: string;
  updatedAt: string;
}

/**
 * ====================================== Orders ======================================//
 * ==================== GetManyOrdersRequest ====================//
 */
export interface GetManyOrdersRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  paymentId?: string | undefined;
  status?: string | undefined;
  userId?: string | undefined;
  shopId?: string | undefined;
}

export interface OrderSummary {
  id: string;
  shopId: string;
  shopName: string;
  status: string;
  itemTotal: number;
  grandTotal: number;
  firstProductImage: string;
  firstProductName: string;
}

export interface GetManyOrdersResponse {
  orders: OrderSummary[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== GetOrderRequest ====================// */
export interface GetOrderRequest {
  processId?: string | undefined;
  orderId: string;
  userId?: string | undefined;
  shopId?: string | undefined;
}

export interface Receiver {
  name: string;
  phoneNumber: string;
  address: string;
}

export interface Timeline {
  status: string;
  at: string;
}

export interface OrderItemSnapshot {
  id: string;
  productId: string;
  productImage: string;
  productName: string;
  skuValue: string;
  quantity: number;
  price: number;
}

export interface GetOrderResponse {
  id: string;
  code: string;
  userId: string;
  shopId: string;
  shopName: string;
  status: string;
  paymentMethod: string;
  paymentStatus: string;
  paymentId: string;
  itemTotal: number;
  shippingFee: number;
  discount: number;
  grandTotal: number;
  receiver: Receiver | undefined;
  receiverName: string;
  receiverPhone: string;
  receiverAddress: string;
  timeline: Timeline | undefined;
  itemsSnapshot: OrderItemSnapshot[];
  firstProductName: string;
  firstProductImage: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * ====================================== Video ======================================//
 * ==================== GetVideoRequest ====================//
 */
export interface GetVideoRequest {
  processId?: string | undefined;
  id: string;
  status?: string | undefined;
}

export interface VideoResponse {
  id: string;
  storageBucket: string;
  storageKey: string;
  filetype: string;
  size: number;
  status: string;
  duration: number;
  width: number;
  height: number;
  createdAt: string;
  updatedAt: string;
  title: string;
  likeCount: number;
  commentCount: number;
  authorId: string;
  authorUsername?: string | undefined;
  authorAvatar?: string | undefined;
}

/** ==================== GetManyVideosRequest ====================// */
export interface GetManyVideosRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId?: string | undefined;
  status?: string | undefined;
  title?: string | undefined;
}

export interface VideoBasicInfo {
  id: string;
  size: number;
  duration: number;
  width: number;
  height: number;
  status: string;
  title: string;
  likeCount: number;
  commentCount: number;
  authorId: string;
}

export interface GetManyVideosResponse {
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
  videos: VideoBasicInfo[];
}

export const QUERY_SERVICE_PACKAGE_NAME = "QUERY_SERVICE";

export interface QueryServiceClient {
  getCategory(request: GetCategoryRequest): Observable<GetCategoryResponse>;

  getManyCategories(request: GetManyCategoriesRequest): Observable<GetManyCategoriesResponse>;

  getBrand(request: GetBrandRequest): Observable<GetBrandResponse>;

  getManyBrands(request: GetManyBrandsRequest): Observable<GetManyBrandsResponse>;

  getAttribute(request: GetAttributeRequest): Observable<GetAttributeResponse>;

  getManyAttributes(request: GetManyAttributesRequest): Observable<GetManyAttributesResponse>;

  getProduct(request: GetProductRequest): Observable<GetProductResponse>;

  getManyProducts(request: GetManyProductsRequest): Observable<GetManyProductsResponse>;

  getNotification(request: GetNotificationRequest): Observable<NotificationResponse>;

  getManyNotifications(request: GetManyNotificationsRequest): Observable<GetManyNotificationsResponse>;

  getManyOrders(request: GetManyOrdersRequest): Observable<GetManyOrdersResponse>;

  getOrder(request: GetOrderRequest): Observable<GetOrderResponse>;

  getManyVideos(request: GetManyVideosRequest): Observable<GetManyVideosResponse>;

  getVideo(request: GetVideoRequest): Observable<VideoResponse>;
}

export interface QueryServiceController {
  getCategory(
    request: GetCategoryRequest,
  ): Promise<GetCategoryResponse> | Observable<GetCategoryResponse> | GetCategoryResponse;

  getManyCategories(
    request: GetManyCategoriesRequest,
  ): Promise<GetManyCategoriesResponse> | Observable<GetManyCategoriesResponse> | GetManyCategoriesResponse;

  getBrand(request: GetBrandRequest): Promise<GetBrandResponse> | Observable<GetBrandResponse> | GetBrandResponse;

  getManyBrands(
    request: GetManyBrandsRequest,
  ): Promise<GetManyBrandsResponse> | Observable<GetManyBrandsResponse> | GetManyBrandsResponse;

  getAttribute(
    request: GetAttributeRequest,
  ): Promise<GetAttributeResponse> | Observable<GetAttributeResponse> | GetAttributeResponse;

  getManyAttributes(
    request: GetManyAttributesRequest,
  ): Promise<GetManyAttributesResponse> | Observable<GetManyAttributesResponse> | GetManyAttributesResponse;

  getProduct(
    request: GetProductRequest,
  ): Promise<GetProductResponse> | Observable<GetProductResponse> | GetProductResponse;

  getManyProducts(
    request: GetManyProductsRequest,
  ): Promise<GetManyProductsResponse> | Observable<GetManyProductsResponse> | GetManyProductsResponse;

  getNotification(
    request: GetNotificationRequest,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  getManyNotifications(
    request: GetManyNotificationsRequest,
  ): Promise<GetManyNotificationsResponse> | Observable<GetManyNotificationsResponse> | GetManyNotificationsResponse;

  getManyOrders(
    request: GetManyOrdersRequest,
  ): Promise<GetManyOrdersResponse> | Observable<GetManyOrdersResponse> | GetManyOrdersResponse;

  getOrder(request: GetOrderRequest): Promise<GetOrderResponse> | Observable<GetOrderResponse> | GetOrderResponse;

  getManyVideos(
    request: GetManyVideosRequest,
  ): Promise<GetManyVideosResponse> | Observable<GetManyVideosResponse> | GetManyVideosResponse;

  getVideo(request: GetVideoRequest): Promise<VideoResponse> | Observable<VideoResponse> | VideoResponse;
}

export function QueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getCategory",
      "getManyCategories",
      "getBrand",
      "getManyBrands",
      "getAttribute",
      "getManyAttributes",
      "getProduct",
      "getManyProducts",
      "getNotification",
      "getManyNotifications",
      "getManyOrders",
      "getOrder",
      "getManyVideos",
      "getVideo",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const QUERY_SERVICE_NAME = "QueryService";
