// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: query.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "QUERY_SERVICE";

/** ====================================== Category ======================================// */
export interface CategoryProduct {
  id: string;
  name: string;
  logo: string;
  parentCategoryId?: string | undefined;
}

/** ==================== GetCategoryRequest ====================// */
export interface GetCategoryRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetCategoryResponse {
  id: string;
  name: string;
  logo: string;
  parentId?: string | undefined;
  path: string;
  level: number;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyCategoriesRequest ====================// */
export interface GetManyCategoriesRequest {
  processId?: string | undefined;
  parentCategoryId?: string | undefined;
}

export interface GetManyCategoriesResponse {
  categories: GetCategoryResponse[];
}

/**
 * ====================================== Brand ======================================//
 * ==================== GetBrandRequest ====================//
 */
export interface GetBrandRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetBrandResponse {
  id: string;
  name: string;
  logo: string;
  productsCount: number;
  soldCount: number;
  categoryIds: string[];
  categories: CategoryProduct[];
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyBrandsRequest ====================// */
export interface GetManyBrandsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyBrandsResponse {
  brands: GetBrandResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Attribute ======================================//
 * ==================== GetAttributeRequest ====================//
 */
export interface GetAttributeRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetAttributeResponse {
  id: string;
  name: string;
  categoryIds: string[];
  categories: CategoryProduct[];
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyAttributesRequest ====================// */
export interface GetManyAttributesRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
}

export interface GetManyAttributesResponse {
  attributes: GetAttributeResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== ShipsFrom ======================================//
 * ==================== GetShipsFromRequest ====================//
 */
export interface GetShipsFromRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetShipsFromResponse {
  id: string;
  address: string;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyShipsFromRequest ====================// */
export interface GetManyShipsFromRequest {
  processId?: string | undefined;
  address?: string | undefined;
}

export interface GetManyShipsFromResponse {
  shipsFromList: GetShipsFromResponse[];
}

/** ====================================== Product ======================================// */
export interface Variant {
  value: string;
  options: string[];
}

export interface AttributeProduct {
  name: string;
  value: string;
}

export interface SKU {
  id: string;
  value: string;
  price: number;
  stock: number;
  image?: string | undefined;
}

/** ==================== GetProductRequest ====================// */
export interface GetProductRequest {
  processId?: string | undefined;
  id: string;
}

export interface GetProductResponse {
  id: string;
  name: string;
  description?: string | undefined;
  shipsFromId: string;
  shipsFromAddress: string;
  brandId?: string | undefined;
  brandName?: string | undefined;
  brandLogo?: string | undefined;
  categoryIds: string[];
  categories: CategoryProduct[];
  basePrice: number;
  virtualPrice: number;
  minPrice: number;
  maxPrice: number;
  totalStock: number;
  isAvailable: boolean;
  images: string[];
  sizeGuide?: string | undefined;
  variants: Variant[];
  attributes: AttributeProduct[];
  skus: SKU[];
  reviewIds: string[];
  ratingCount: number;
  averageRate: number;
  soldCount: number;
  viewCount: number;
  likeCount: number;
  shopId: string;
  status: string;
  isApproved: boolean;
  isHidden: boolean;
  createdAt: string;
  updatedAt: string;
}

/** ==================== GetManyProductsRequest ====================// */
export interface GetManyProductsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  name?: string | undefined;
  status?: string | undefined;
  shopId?: string | undefined;
  brandIds: string[];
  categories: string[];
  minPrice?: number | undefined;
  maxPrice?: number | undefined;
  sortBy?: string | undefined;
  orderBy?: string | undefined;
}

export interface GetManyProductsResponse {
  products: GetProductResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/**
 * ====================================== Notifications ======================================//
 * ==================== GetManyNotificationsRequest ====================//
 */
export interface GetManyNotificationsRequest {
  processId?: string | undefined;
  page: number;
  limit: number;
  userId: string;
}

export interface GetManyNotificationsResponse {
  notifications: NotificationResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface Metadata {
  orderId?: string | undefined;
  articleId?: string | undefined;
}

export interface NotificationResponse {
  id: string;
  userId: string;
  type: string;
  title: string;
  description: string;
  link?: string | undefined;
  image?: string | undefined;
  isRead: boolean;
  metadata?: Metadata | undefined;
  createdAt: string;
  updatedAt: string;
}

export const QUERY_SERVICE_PACKAGE_NAME = "QUERY_SERVICE";

export interface QueryServiceClient {
  getCategory(request: GetCategoryRequest): Observable<GetCategoryResponse>;

  getManyCategories(request: GetManyCategoriesRequest): Observable<GetManyCategoriesResponse>;

  getBrand(request: GetBrandRequest): Observable<GetBrandResponse>;

  getManyBrands(request: GetManyBrandsRequest): Observable<GetManyBrandsResponse>;

  getAttribute(request: GetAttributeRequest): Observable<GetAttributeResponse>;

  getManyAttributes(request: GetManyAttributesRequest): Observable<GetManyAttributesResponse>;

  getShipsFrom(request: GetShipsFromRequest): Observable<GetShipsFromResponse>;

  getManyShipsFrom(request: GetManyShipsFromRequest): Observable<GetManyShipsFromResponse>;

  getProduct(request: GetProductRequest): Observable<GetProductResponse>;

  getManyProducts(request: GetManyProductsRequest): Observable<GetManyProductsResponse>;

  getManyNotifications(request: GetManyNotificationsRequest): Observable<GetManyNotificationsResponse>;
}

export interface QueryServiceController {
  getCategory(
    request: GetCategoryRequest,
  ): Promise<GetCategoryResponse> | Observable<GetCategoryResponse> | GetCategoryResponse;

  getManyCategories(
    request: GetManyCategoriesRequest,
  ): Promise<GetManyCategoriesResponse> | Observable<GetManyCategoriesResponse> | GetManyCategoriesResponse;

  getBrand(request: GetBrandRequest): Promise<GetBrandResponse> | Observable<GetBrandResponse> | GetBrandResponse;

  getManyBrands(
    request: GetManyBrandsRequest,
  ): Promise<GetManyBrandsResponse> | Observable<GetManyBrandsResponse> | GetManyBrandsResponse;

  getAttribute(
    request: GetAttributeRequest,
  ): Promise<GetAttributeResponse> | Observable<GetAttributeResponse> | GetAttributeResponse;

  getManyAttributes(
    request: GetManyAttributesRequest,
  ): Promise<GetManyAttributesResponse> | Observable<GetManyAttributesResponse> | GetManyAttributesResponse;

  getShipsFrom(
    request: GetShipsFromRequest,
  ): Promise<GetShipsFromResponse> | Observable<GetShipsFromResponse> | GetShipsFromResponse;

  getManyShipsFrom(
    request: GetManyShipsFromRequest,
  ): Promise<GetManyShipsFromResponse> | Observable<GetManyShipsFromResponse> | GetManyShipsFromResponse;

  getProduct(
    request: GetProductRequest,
  ): Promise<GetProductResponse> | Observable<GetProductResponse> | GetProductResponse;

  getManyProducts(
    request: GetManyProductsRequest,
  ): Promise<GetManyProductsResponse> | Observable<GetManyProductsResponse> | GetManyProductsResponse;

  getManyNotifications(
    request: GetManyNotificationsRequest,
  ): Promise<GetManyNotificationsResponse> | Observable<GetManyNotificationsResponse> | GetManyNotificationsResponse;
}

export function QueryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getCategory",
      "getManyCategories",
      "getBrand",
      "getManyBrands",
      "getAttribute",
      "getManyAttributes",
      "getShipsFrom",
      "getManyShipsFrom",
      "getProduct",
      "getManyProducts",
      "getManyNotifications",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("QueryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const QUERY_SERVICE_NAME = "QueryService";
