// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: role.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ROLE_SERVICE";

/** ==================== GetRole ====================// */
export interface GetRoleRequest {
  processId?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
}

export interface RoleResponse {
  id: string;
  name: string;
  description: string;
  userIds: string[];
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  permissions: string[];
}

/** ==================== GetRoleWithoutUserIds ====================// */
export interface RoleWithoutUserIdsResponse {
  id: string;
  name: string;
  description: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
  permissions: string[];
}

/** ==================== GetManyRoles ====================// */
export interface GetManyRolesRequest {
  processId?: string | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface GetManyRolesResponse {
  roles: RoleResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** ==================== CreateRole ====================// */
export interface CreateRoleRequest {
  processId?: string | undefined;
  name: string;
  description: string;
}

/** ==================== UpdateRole ====================// */
export interface UpdateRoleRequest {
  processId?: string | undefined;
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  updatedById: string;
  permissionIds: string[];
}

/** ==================== DeleteRole ====================// */
export interface DeleteRoleRequest {
  processId?: string | undefined;
  id: string;
  deletedById: string;
}

export const ROLE_SERVICE_PACKAGE_NAME = "ROLE_SERVICE";

export interface RoleServiceClient {
  getRole(request: GetRoleRequest): Observable<RoleResponse>;

  getRoleWithoutUserIds(request: GetRoleRequest): Observable<RoleWithoutUserIdsResponse>;

  getManyRoles(request: GetManyRolesRequest): Observable<GetManyRolesResponse>;

  createRole(request: CreateRoleRequest): Observable<RoleWithoutUserIdsResponse>;

  updateRole(request: UpdateRoleRequest): Observable<RoleWithoutUserIdsResponse>;

  deleteRole(request: DeleteRoleRequest): Observable<RoleWithoutUserIdsResponse>;
}

export interface RoleServiceController {
  getRole(request: GetRoleRequest): Promise<RoleResponse> | Observable<RoleResponse> | RoleResponse;

  getRoleWithoutUserIds(
    request: GetRoleRequest,
  ): Promise<RoleWithoutUserIdsResponse> | Observable<RoleWithoutUserIdsResponse> | RoleWithoutUserIdsResponse;

  getManyRoles(
    request: GetManyRolesRequest,
  ): Promise<GetManyRolesResponse> | Observable<GetManyRolesResponse> | GetManyRolesResponse;

  createRole(
    request: CreateRoleRequest,
  ): Promise<RoleWithoutUserIdsResponse> | Observable<RoleWithoutUserIdsResponse> | RoleWithoutUserIdsResponse;

  updateRole(
    request: UpdateRoleRequest,
  ): Promise<RoleWithoutUserIdsResponse> | Observable<RoleWithoutUserIdsResponse> | RoleWithoutUserIdsResponse;

  deleteRole(
    request: DeleteRoleRequest,
  ): Promise<RoleWithoutUserIdsResponse> | Observable<RoleWithoutUserIdsResponse> | RoleWithoutUserIdsResponse;
}

export function RoleServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getRole",
      "getRoleWithoutUserIds",
      "getManyRoles",
      "createRole",
      "updateRole",
      "deleteRole",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("RoleService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("RoleService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ROLE_SERVICE_NAME = "RoleService";
