// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: user-access.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "USER_ACCESS_SERVICE";

/** ==================== Login ====================// */
export interface LoginRequest {
  processId?: string | undefined;
  username: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  refreshExpiresIn: number;
}

/** ==================== Refresh Token ====================// */
export interface RefreshTokenRequest {
  processId?: string | undefined;
  refreshToken: string;
}

export interface LogoutRequest {
  processId?: string | undefined;
  refreshToken: string;
}

/** ==================== Register ====================// */
export interface RegisterRequest {
  processId?: string | undefined;
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  password: string;
  phoneNumber: string;
  gender: string;
}

export interface Empty {
}

/** ==================== Verify Token ====================// */
export interface VerifyTokenRequest {
  processId?: string | undefined;
  token: string;
}

export interface VerifyTokenResponse {
  isValid: boolean;
  id: string;
  roleId: string;
  roleName: string;
  permissions: Permissions[];
}

export interface Permissions {
  id: string;
  path: string;
  method: string;
}

/** ==================== CreateUser ====================// */
export interface CreateUserRequest {
  processId?: string | undefined;
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  phoneNumber: string;
  avatar: string;
  gender: string;
  roleId: string;
  roleName: string;
}

export interface UserResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  phoneNumber: string;
  avatar: string;
  /** ISO 8601 format */
  birthday: string;
  gender: string;
  status: string;
  roleId: string;
  roleName: string;
  createdById: string;
  updatedById: string;
  deletedById: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export const USER_ACCESS_SERVICE_PACKAGE_NAME = "USER_ACCESS_SERVICE";

export interface UserAccessServiceClient {
  loginDirectAccessGrants(request: LoginRequest): Observable<LoginResponse>;

  refreshToken(request: RefreshTokenRequest): Observable<LoginResponse>;

  logout(request: LogoutRequest): Observable<Empty>;

  register(request: RegisterRequest): Observable<Empty>;

  verifyToken(request: VerifyTokenRequest): Observable<VerifyTokenResponse>;

  createUser(request: CreateUserRequest): Observable<UserResponse>;
}

export interface UserAccessServiceController {
  loginDirectAccessGrants(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  refreshToken(request: RefreshTokenRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  logout(request: LogoutRequest): Promise<Empty> | Observable<Empty> | Empty;

  register(request: RegisterRequest): Promise<Empty> | Observable<Empty> | Empty;

  verifyToken(
    request: VerifyTokenRequest,
  ): Promise<VerifyTokenResponse> | Observable<VerifyTokenResponse> | VerifyTokenResponse;

  createUser(request: CreateUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserAccessServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "loginDirectAccessGrants",
      "refreshToken",
      "logout",
      "register",
      "verifyToken",
      "createUser",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserAccessService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserAccessService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_ACCESS_SERVICE_NAME = "UserAccessService";
