// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Report.Infrastructure.Persistence;

#nullable disable

namespace Report.Infrastructure.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260102041427_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Report.Domain.Entities.ReportAction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("IX_ReportActions_ActionType");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("IX_ReportActions_AdminId");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_ReportActions_ReportId");

                    b.ToTable("report_actions");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_ReportComments_ReportId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ReportComments_UserId");

                    b.HasIndex("ReportId", "CreatedAt")
                        .HasDatabaseName("IX_ReportComments_ReportId_CreatedAt");

                    b.ToTable("report_comments");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssignedAdminId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminId")
                        .HasDatabaseName("IX_Reports_AssignedAdminId");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Reports_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Reports_CreatedAt");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Reports_IsDeleted");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("IX_Reports_ReporterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Reports_Status");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("IX_Reports_TargetId");

                    b.HasIndex("TargetType")
                        .HasDatabaseName("IX_Reports_TargetType");

                    b.HasIndex("ReporterId", "IsDeleted")
                        .HasDatabaseName("IX_Reports_ReporterId_IsDeleted");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Reports_Status_CreatedAt");

                    b.HasIndex("TargetId", "TargetType")
                        .HasDatabaseName("IX_Reports_TargetId_TargetType");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportEvidence", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceType")
                        .HasDatabaseName("IX_ReportEvidences_EvidenceType");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_ReportEvidences_ReportId");

                    b.ToTable("report_evidences");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PurgeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("IX_ReportHistories_AdminId");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("IX_ReportHistories_ReportId");

                    b.HasIndex("ReportId", "CreatedAt")
                        .HasDatabaseName("IX_ReportHistories_ReportId_CreatedAt");

                    b.ToTable("report_histories");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportAction", b =>
                {
                    b.HasOne("Report.Domain.Entities.ReportEntity", "Report")
                        .WithMany("Actions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportComment", b =>
                {
                    b.HasOne("Report.Domain.Entities.ReportEntity", "Report")
                        .WithMany("Comments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportEvidence", b =>
                {
                    b.HasOne("Report.Domain.Entities.ReportEntity", "Report")
                        .WithMany("Evidences")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportHistory", b =>
                {
                    b.HasOne("Report.Domain.Entities.ReportEntity", "Report")
                        .WithMany("History")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Comments");

                    b.Navigation("Evidences");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
